### ISSUE TITLE
Installation issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by moldach** [ggonnella/gfapy#12]
I'm having issues trying to install `gfapy` on Ubuntu 20.04 LTS. I've tried each installation method but python is not finding it?

## Regular

```
mtg@mtg-ThinkPad-P53:~/projects/TEST-MOMIG$ pip install gfapy
```

Remove with `pip uninstall gfapy` then,

## Development version

```
mtg@mtg-ThinkPad-P53:~/projects/TEST-MOMIG$ pip install -e git+https://github.com/ggonnella/gfapy.git#egg=gfapy
```

Again remove, then:

## Conda

```
mtg@mtg-ThinkPad-P53: conda activate base
(base) mtg@mtg-ThinkPad-P53:~/projects/TEST-MOMIG$ conda install -c bioconda gfapy
```

After each one I tried the following with the same error:

```
(base) mtg@mtg-ThinkPad-P53:~/projects/TEST-MOMIG$ python
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gfapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gfapy'
```

Any idea what is going on?

**Comment by ggonnella** [comment]
Dear moldach. I cannot reproduce your error. I don't have Ubunto, unfortunately. But on my system, all three methods work... is there maybe some problems with the PATH? Once I had a pip (the system one) which was installing elsewhere than the python on my PATH (which was the conda one)...

**Comment by moldach** [comment]
That was the issue, thanks. Solved by:

```
conda deactivate
python3.8 -m venv ~/bin/gfapy
source ~/bin/gfapy/bin/activate
pip install gfapy
```
