### ISSUE TITLE
gfapy.error.FormatError: Custom tags must be lower case

### ISSUE THREAD

**Issue by Zethson** [ggonnella/gfapy#13]
I have a gfa file, which look as follows: 

S	utg000001l	*
S	utg000002l	*
S	utg000003l	*
S	utg000004l	*
S	utg000005l	*
[...]
L	utg000001l	+	utg058900l	+	12383M	L1:i:913617
L	utg000001l	+	utg062906l	-	12217M	L1:i:913783
L	utg000001l	-	utg028945l	-	13052M	L1:i:912948
L	utg000002l	+	utg043590l	+	10450M	L1:i:587175
L	utg000002l	-	utg044206l	-	18954M	L1:i:578671
[...]

When parsing the file I am running into "gfapy.error.FormatError: Custom tags must be lower case". 
According to the gfa specification, L1:i should be fine?

**Comment by ggonnella** [comment]
Dear Zethson. The problem is that L1 is actually a non-standard compliant tag, since it's upper case and not defined in the specification. Maybe you could have a look to the rgfa branch. https://github.com/ggonnella/gfapy/tree/rgfa I plan to merge it soon with the master branch... In it I introduced a concept of non-standard dialects... so I could define a upper case custom-tags dialect. What is the source of your GFA?

**Comment by Zethson** [comment]
> All optional fields follow the TAG:TYPE:VALUE format where TAG is a two-character string that matches /[A-Za-z][A-Za-z0-9]/. Each TAG can only appear once in one line. A TAG containing lowercase letters are reserved for end users. A TYPE is a single case-sensitive letter which defines the format of VALUE.

To me this allows for uppercase tags? Source: https://gfa-spec.github.io/GFA-spec/GFA1.html

It's an internal GFA, which was handed to me. I cannot tell you where they got it from, since I do not know it either. gfatools does handle it by the way.

**Comment by ggonnella** [comment]
It looks like you are right. At a certain point in the past, it must have been different, I guess. Or I understood it wrongly, somehow. I fix it and make a new release.

**Comment by ggonnella** [comment]
I released version 1.1.0, which fixes this bug. Thank you again for reporting the issue. If possible, test it again with the file you have...

**Comment by Zethson** [comment]
Works, thanks!
