### ISSUE TITLE
validating paths

### ISSUE THREAD

**Issue by egoltsman** [ggonnella/gfapy#14]
Hello,
I'm wondering if gfapy includes methods for validating paths.  It's possible to add a path (ordered or unordered) to a subgraph, where some path elements are missing from the graph, i.e. they're not present as a valid segment or edge.  If wholesale path validation doesn't check for this, I could just write my own method that checks every path segment for "existence".  I was looking for a convenient boolean test that would just tell me that but didn't find it (or didn't know where to look)

Thanks!

**Comment by ggonnella** [comment]
Yes. By default gfapy validates each path, and would output an error at then end of parsing the input, if an element of a path does not exist.

If you want to turn off the validation, you must use the option ``vlevel=0`` when you create the ``Gfa`` object (i.e. when calling ``Gfa.from_file()`` or ``Gfa()``). In this case a "virtual" line is created representing the missing and required element.

**Comment by egoltsman** [comment]
It seems that instead of throwing an error it creates "virtual" edges.  Is that intended behavior?

Here I'm adding a path that contains bogus elements, and the code executes without errors

```
gfa=gfapy.Gfa.from_file("Bd21Ref.Bd21_3.Bd21-3_r.gfa", dialect="rgfa")
fooPath = gfapy.Line('P\tfooPath\ts1foo+,s1foooo+\t*')
assert (type(fooPath) == gfapy.line.group.path.path.Path), "line object is not of valid Path type"
gfa.add_line(fooPath)
gfa.path_names

$ ['fooPath']

's1foooo' in gfa.names
 
$ True

gfa.line('s1foooo')

$ gfapy.Line('S	s1foooo	*	co:Z:GFAPY_virtual_line',version='gfa1',vlevel=1)
```

I ended up adding a quick check of my own, which I'm happy to keep, but if you say this should be part of validation then perhaps there's a bug.   Note, the gfa object was created with the 'rgfa' dialect.  Could that be the issue?

**Comment by ggonnella** [comment]
Commit 4e06a1c adds a test with a small example of invalid and valid path and validation.

**Comment by egoltsman** [comment]
That works :) Thanks!
