### ISSUE TITLE
conversion between GFA and GFA2 leaves out path tags

### ISSUE THREAD

**Issue by egoltsman** [ggonnella/gfapy#19]
Hi,
When using the to_gfa2 and to_gfa1 methods (same for to_gfa*_s),  any tags in the path lines, whether ordered or unordered, are ignored and not transferred to the new object.  Since tags are generally legal to all lines in both GFA and GFA2 (please correct me if I'm wrong here), this should probably be fixes.

Thanks

**Comment by ggonnella** [comment]
Thank you. The new commit should fix this.
