### ISSUE TITLE
gfa-convert: custom sl:i tag ought to be LN:i

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfapy#5]
I'm guessing here that `sl:i` is sequence length. The standard name for this tag is `LN:i`
See https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md#optional-fields-2
Observed output
```
S	A	AAAAAAACGT	sl:i:10
```
Expected output
```
S	A	AAAAAAACGT	LN:i:10
```

**Comment by ggonnella** [comment]
It was LN, and I changed it to sl, as the content of the slen tag does not really need to be the length of the segment, according to the GFA2 specification. Maybe, if the sequence is available, I can change it to LN if it agrees with its length.

**Comment by sjackman** [comment]
I never did like that bit of the GFA 2 spec. It's peculiar. I would go with `LN:i` all the same. If the sequence is not present, then I would definitely use `LN:i`. If the sequence is present, then I wouldn't include any `LN:i` tag at all.

**Comment by ggonnella** [comment]
I also do not like it, I never understood the reason for that...

**Comment by sjackman** [comment]
> If the sequence is present, then I wouldn't include any LN:i tag at all.

On second thought, do you think it's helpful to always include the `LN:i` tag in GFA 1 output?

**Comment by ggonnella** [comment]
Yes, I think that if the information is there, one can output it.
